name: complex_sample_project
version: 1.0.0
config-version: 2
profile: complex_sample_project
model-paths:
- models
analysis-paths:
- analyses
test-paths:
- tests
seed-paths:
- seeds
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  complex_sample_project:
    staging:
      +materialized: view
      +tags:
      - staging
    intermediate:
      +materialized: table
      +tags:
      - intermediate
    marts:
      +materialized: table
      +tags:
      - marts
seeds:
  complex_sample_project:
    +quote_columns: false
